---
kind: pipeline
type: docker
name: test
trigger:
  branch:
    - master
steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      tags: ${DRONE_COMMIT}
  - name: test
    depends_on: [build]
    image: platyplus/drone-gcloud:${DRONE_COMMIT}
    settings:
      credentials:
        from_secret: google_credentials
      config:
        - project: platyplus-0402
        - compute/region: europe-west1
        - compute/zone: europe-west1-b
        - run/platform: managed
        - run/region: europe-west1
      exports:
        CLOUDSQL_INSTANCE: sql instances describe platyplus --format="get(connectionName)"
      commands:
        - 'sql instances describe platyplus --format="get(connectionName)"'
      mixed:
        - CLOUDSQL_INSTANCE: 'sql instances describe platyplus --format="get(connectionName)"'
        - 'direct command'
---
kind: pipeline
type: docker
name: deploy
trigger:
  branch:
    - master
depends_on: [test]
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      auto_tag: true
      tags: latest
---
kind: signature
hmac: 629accbae35de12e99c8bb3aa3e26027fc9cade1a3bb02a4785cd8d273bf6936

...
