---
kind: pipeline
type: docker
name: test
trigger:
  branch:
    - master
steps:
  - name: build
    image: plugins/docker
    settings:
      dry_run: true
      repo: platyplus/drone-gcloud
      tags: latest
  - name: publish
    depends_on: [build]
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      auto_tag: true
      tags: latest
---
kind: pipeline
type: docker
name: deploy
trigger:
  branch:
    - master
depends_on: [test]
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      auto_tag: true
      tags: latest
---
kind: signature
hmac: d6d667bdc846550602532e0aab1ce2bfdb35329d3076e7ce5737d320603cc7a6
