---
kind: pipeline
type: docker
name: deploy
trigger:
  branch:
    - master
depends_on: [test]
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      auto_tag: true
      tags: latest
---
kind: signature
hmac: f5c01614c00d5f3ef31e56c94c035d923d0908f13521cf0c1a8bc2cd10538a70
