---
kind: pipeline
type: docker
name: test
trigger:
  branch:
    - master
steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      tags: ${DRONE_COMMIT}
  - name: test
    depends_on: [build]
    image: platyplus/drone-gcloud:${DRONE_COMMIT}
    environment:
      CREDENTIALS:
        from_secret: google_credentials
    settings:
      CREDENTIALS:
        from_secret: google_credentials
      config:
        - project: platyplus-0402
        - compute/region: europe-west1
        - compute/zone: europe-west1-b
        - run/platform: managed
        - run/region: europe-west1
      commands:
        - 'sql instances describe platyplus --format="get(connectionName)"'
        - CLOUDSQL_INSTANCE: 'sql instances describe platyplus --format="get(connectionName)"'
      t1:
        - 'one string'
        - another string
      t2:
        - one string
        - another
      t3:
        - param: value1
        - param2: value2
---
kind: pipeline
type: docker
name: deploy
trigger:
  branch:
    - master
depends_on: [test]
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      auto_tag: true
      tags: latest
---
kind: signature
hmac: db18658f8aa4c39c21d2d8e7dbdf35f426a0938b991dc74f9b191e27781f4cc8
