---
kind: pipeline
type: docker
name: deploy
trigger:
  branch:
    - master
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_TOKEN
      repo: platyplus/drone-gcloud
      auto_tag: true
      tags: latest
---
kind: signature
hmac: 7f1c1ca3a419e37b3fe4484c5639adcfbcf65b110fc8819c1ea64f24a981eee9

...
